name: Delete Old GitHub Actions Runs

on:
  workflow_dispatch:
    inputs:
      days-ago:
        description: "Delete workflow runs older than this many days"
        required: true
        default: "30"

jobs:
  delete-old-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-ago: ${{ inputs.days-ago }}